# Generated by Django 6.0 on 2025-12-17 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdvertisementElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        help_text="The display text or identifier for the advertisement element.",
                        max_length=255,
                        verbose_name="Display",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The code or identifier for the advertisement element.",
                        max_length=100,
                        verbose_name="Code",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvertisementKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="The display name for the advertisement kind.",
                        max_length=255,
                        verbose_name="Display Name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the customer company or individual.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "ruc",
                    models.CharField(
                        help_text="The RUC (Registro Único de Contribuyente) tax identification number. Must be unique.",
                        max_length=20,
                        unique=True,
                        verbose_name="RUC",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The primary email address for the customer.",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="The primary phone number for the customer.",
                        max_length=20,
                        verbose_name="Phone",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="The complete address of the customer.",
                        verbose_name="Address",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        help_text="The name of the primary contact person for this customer.",
                        max_length=255,
                        verbose_name="Contact Name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp indicating when the customer record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp indicating when the customer record was last modified.",
                        verbose_name="Updated At",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the seller or sales representative.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="The complete address of the seller.",
                        verbose_name="Address",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The primary email address for the seller.",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="The name of the company the seller represents.",
                        max_length=255,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "ruc",
                    models.CharField(
                        help_text="The RUC (Registro Único de Contribuyente) tax identification number of the seller's company.",
                        max_length=20,
                        verbose_name="RUC",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ruc",
                    models.CharField(
                        help_text="The RUC (Registro Único de Contribuyente) tax identification number for the order.",
                        max_length=20,
                        verbose_name="RUC",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The email address associated with the order.",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="The delivery or billing address for the order.",
                        verbose_name="Address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="The phone number associated with the order.",
                        max_length=20,
                        verbose_name="Phone",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        help_text="The name of the contact person for this order.",
                        max_length=255,
                        verbose_name="Contact Name",
                    ),
                ),
                (
                    "payment_days",
                    models.PositiveIntegerField(
                        help_text="The number of days for payment terms for the order. Must be a positive integer.",
                        verbose_name="Payment Days",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The customer who placed this order.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="brave_orders.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="The seller who is fulfilling this order.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="brave_orders.seller",
                        verbose_name="Seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        help_text="The brand name associated with the advertisement.",
                        max_length=255,
                        verbose_name="Brand",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The code or identifier for the advertisement.",
                        max_length=100,
                        verbose_name="Code",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="The start date when the advertisement begins.",
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="The end date when the advertisement expires.",
                        verbose_name="End Date",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="The quantity of advertisement units. Must be a positive integer.",
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The unit price for each advertisement item.",
                        max_digits=10,
                        verbose_name="Unit Price",
                    ),
                ),
                (
                    "advertisement_element",
                    models.ForeignKey(
                        help_text="The advertisement element associated with this advertisement.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advertisements",
                        to="brave_orders.advertisementelement",
                        verbose_name="Advertisement Element",
                    ),
                ),
                (
                    "advertisement_kind",
                    models.ForeignKey(
                        help_text="The advertisement kind associated with this advertisement.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advertisements",
                        to="brave_orders.advertisementkind",
                        verbose_name="Advertisement Kind",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The order that contains this advertisement.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advertisements",
                        to="brave_orders.order",
                        verbose_name="Order",
                    ),
                ),
            ],
        ),
    ]
