# Generated by Django 6.0 on 2025-12-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "ruc",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="RUC"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Phone"),
                ),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "contact_name",
                    models.CharField(
                        max_length=255, verbose_name="Contact Name"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated At"
                    ),
                ),
            ],
        ),
    ]
