# Generated by Django 6.0 on 2025-12-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brave_orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the seller or sales representative.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="The complete address of the seller.",
                        verbose_name="Address",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The primary email address for the seller.",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="The name of the company the seller represents.",
                        max_length=255,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "company_ruc",
                    models.CharField(
                        help_text="The RUC (Registro Único de Contribuyente) tax identification number of the seller's company.",
                        max_length=20,
                        verbose_name="Company RUC",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(
                help_text="The complete address of the customer.",
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="contact_name",
            field=models.CharField(
                help_text="The name of the primary contact person for this customer.",
                max_length=255,
                verbose_name="Contact Name",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp indicating when the customer record was created.",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                help_text="The primary email address for the customer.",
                max_length=254,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(
                help_text="The full name of the customer company or individual.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                help_text="The primary phone number for the customer.",
                max_length=20,
                verbose_name="Phone",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="ruc",
            field=models.CharField(
                help_text="The RUC (Registro Único de Contribuyente) tax identification number. Must be unique.",
                max_length=20,
                unique=True,
                verbose_name="RUC",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp indicating when the customer record was last modified.",
                verbose_name="Updated At",
            ),
        ),
    ]
